export interface Product {
    productId: number;
    productType: string;
    feeType: string;
    organizationName: string;
    organizationId: number;
    productName: string;
    orderUrl: string;
    vatApplicable: boolean;
    elCertificateApplicable: boolean;
    maxKWYear: number | null;
    addonPriceMinimumFixedFor: number;
    addonPriceMinimumFixedForUnits: string;
    currentPrice: {
      monthlyFee: number;
      addonPrice: number;
      purchaseAddonPrice: number | null;
      kwPrice: number;
      purchaseKwPrice: number | null;
      spotPrice: number;
      vatRatio: number;
      consumerElectricityTax: number;
      usageMonthlyProfile: number;
      feeMail: number;
      contractBreachFee: number;
    };
    memberships: any[];
    elCertificatePrice: number;
    priceType: null;
    purchasePriceType: null;
    cabinProduct: boolean;
    expired: boolean;
    standardAlert: string;
    applicableToCustomersType: string;
    otherConditions: null;
    agreementTime: number;
    agreementTimeUnits: string;
    billingFrequency: number;
    billingFrequencyUnits: string;
    feeEFakturaMandatory: boolean;
    feeAvtalegiroMandatory: boolean;
    activeComplaint: boolean;
    priceUpdatedDate: string;
    finalAddonPrice: number;
    finalMonthlyFee: number;
    finalFeeMail: number;
    finalContractBreachFee: number;
    finalKwPrice: number;
    electricityPerKwh: number;
    monthlyConsumption: null;
    fixedMonthlyElectricityPrice: number;
    electricityMonthlyConsumptionPrice: null;
    fullMonthlyElectricityPrice: null;
    effectiveAddon: null;
    finalPriceMonthly: null;
    finalPriceAddon: null;
    addonPriceMinimumFixedForInMonths: number;
    agreementTimeInMonths: number;
  }